config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'products#index'
  resources :products do
    resources :reviews, except: [:index, :new, :show]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
has_many :reviews

validates :name, :description, :price_in_cents, presence: true
validates :price_in_cents, numericality: {only_integer: true}

  def price_in_dollars
    price_in_dollars = price_in_cents.to_f / 100
    sprintf("$%.2f", price_in_dollars)
  end

end

app/models/review.rb
class Review < ApplicationRecord


  belongs_to :product
  validates :comment, presence: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
    @review = Review.new
  end

  def new
    @product = Product.new
  end

  def product_params
    {name: params[:product][:name], description: params[:product][:description], price_in_cents: params[:product][:price_in_cents]}
  end

  def create
    @product = Product.create(product_params)
    if @product.save
      flash[:notice] = "Product saved!"
      redirect_to products_path
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      flash[:notice] = "Product udpated!"
      redirect_to @product
    else
      redirect_back_or_to @product
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    flash[:alert] = "Product deleted!"
    redirect_to "/products"
  end

  def product_params
    params.required(:product).permit(:name, :description, :price_in_cents)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def create
    @product = Product.find(params[:product_id])
    @review = @product.reviews.create(review_params)
    if @review.save
      flash[:notice] = "Review saved!"
      redirect_to products_path
    else
      render '/products/show'
    end
  end

  def edit
  @product = Product.find(params[:product_id])
  @review = Review.find(params[:id])
  end

  def update
    @product = Product.find(params[:product_id])
    @review = @product.reviews.find(params[:id])
    if @review.update(review_params)
    # if @product.reviews.update(review_params)
      flash[:notice] = "Review Updated!"
      redirect_to products_path(:product_id)
    else
      redirect_back_or_to @review
    end
  end

  def destroy
  @product = Product.find(params[:product_id])
  @review = Review.find(params[:id])
  @review.destroy
  flash[:alert] = "Review Deleted!"
  redirect_to products_path(:product_id)
  end

  def review_params
    params.required(:review).permit( :comment, :rating)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rainforest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <a href="<%= root_path %>">Home</a>
    </nav>
    <% if flash[:notice] %>
    <p class="notice"><%= flash[:notice] %></p>
    <% end %>
    <% if flash[:alert] %>
      <p class="alert"><%= flash[:alert] %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </p>
  <p>
    <%= f.label :price_in_cents %><br>
    <%= f.number_field :price_in_cents %>
  </p>
  <p>
    <%= f.submit "Save" %>
  </p>
<% end %>

app/views/products/edit.html.erb
<h1>Edit Product</h1>
<% if @product.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

    <ul>
    <% @product.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
   </ul>
 </div>
<% end %>

<%= render 'form', product: @product %>

app/views/products/index.html.erb
<h1> All Products</h1>

<%=link_to("Add New Product", new_product_path) %>

  <% @products.each do |product| %>
  <p><%=link_to(product.name, product_path(product.id))%>, <%=product.description%>, <%=product.price_in_dollars%></p>
  <%end%>

app/views/products/new.html.erb
<h1>Add Product</h1>
<% if @product.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

    <ul>
    <% @product.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
   </ul>
 </div>
<% end %>

<%= render 'form', product: @product %>

app/views/products/show.html.erb
<%=link_to("Edit", edit_product_path(@product.id)) %> |
<%=link_to("Delete", product_path(@product.id), method: :delete, data: {confirm: "Are you sure you want to delete?"}) %>

<p><%=@product.name%>, <%=@product.description%>, <%=@product.price_in_dollars%></p>


<!--ADD NEW REVIEW  -->

<h4>New Review</h4>

<%= render '/reviews/form', review: @review %>

<% if @product.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

    <ul>
    <% @product.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
   </ul>
 </div>
<% end %>



<!--LIST existing reviews  -->
<div class="Reviews">

 <ol>
   <% @product.reviews.each do |review| %>
   <li>
     <%=link_to("Edit", edit_product_review_path(@product, review)) %> |
     <%=link_to("Delete",product_review_path(@product, review), method: :delete, data: {confirm: "Are you sure you want to delete?"}) %>
     <p><%= review.created_at %></p>
      <p><%= review.comment %></p>
      <p><%= review.rating %></p>
   </li>
   <% end %>
 </ol>

</div>

<

app/views/reviews/_form.html.erb
<%= form_for([@product, review]) do |f| %>

  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_area :comment %>
  </div>
  <div class="field">
    <%= f.label :rating %><br />
    <%= f.number_field :rating %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Edit Review</h1>
<% if @review.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@review.errors.count, "error") %> prohibited this product from being saved:</h2>

    <ul>
    <% @review.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
   </ul>
 </div>
<% end %>

<%= render 'reviews/form', review: @review %>